### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Markus-Go/bonesi#1]
```
What steps will reproduce the problem?
1. ./configure
2. make then the error attached
3.

What is the expected output? What do you see instead?
I was expecting it to make without problem after a successful ./configure

What version of the product are you using? On what operating system?
downloaded on march 19th

Please provide any additional information below.
file attached 

```

Original issue reported on code.google.com by `jferdin...@gmail.com` on 19 Mar 2009 at 6:06

Attachments:
- [bonesi.png](https://storage.googleapis.com/google-code-attachments/bonesi/issue-1/comment-0/bonesi.png)

**Comment by Markus-Go** [comment]
This error was due to missing header files of libnet. 
In version 0.1.1 configure checks now if installed.

Original comment by Markus-Go on 5 Feb 2010 at 1:20

* Changed state: **Fixed**
