### ISSUE TITLE
Dependency / Install Script

### ISSUE THREAD

**Issue by kkirsche** [Markus-Go/bonesi#23]
Hey,

I was working on a Kali install script for use in our test lab to automate grabbing the dependencies, installing them, installing this tool, and then cleaning up after the install. You can check the completed one out here:
https://github.com/kkirsche/install-BoNeSi

My question though, do you have interest in me expanding this to include support for ubuntu, centos, rhel, etc. so that you can provide/use a simple install script instead of having to figure out what dependencies this needs based on the errors it throws when either configuring or making?

If so, let me know and I'll expand it for other OS's and then submit a pull request to this repo.

**Comment by Markus-Go** [comment]
Hi,

Thank you for your script and your offer.
I think I prefer the ./configure && make && make install way ...

Missing dependencies are also outlined by the configure script and sometimes people don't want the bins installed into their system, so I would like to have the flexibility ... anyway your script doesn't check for make and gcc ;o)

As a little remark for your script, there is no need to use the specific automake. Try to use the one from your Linux distribution and regenerate the aclocal.m4 using autoreconf (and automake)

Cheers!

**Comment by kkirsche** [comment]
@Markus-Go Understood. And yeah, I don't check for make or gcc as those are even in kali's minimal install. Hence there is no point if the script will reject any other OS. And I tried other ones and the make kept barfing complaining it wasn't the right version of automake so I had to be annoyingly specific.

**Comment by kkirsche** [comment]
Thanks for the feedback though! I'll incorporate it in an update to try to make it better so it'll play nice
