### ISSUE TITLE
configure.ac:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated. 

### ISSUE THREAD

**Issue by fatihusta** [Markus-Go/bonesi#25]
OS: ubuntu server 14.04

Probem
```
 cd . && automake-1.14 --foreign
configure.ac:6: warning: AM_INIT_AUTOMAKE: two- and three-arguments forms are deprecated.  For more info, see:
configure.ac:6: http://www.gnu.org/software/automake/manual/automake.html#Modernize-AM_005fINIT_005fAUTOMAKE-invocation
```

Fix
```
--- /opt/BoNeSi/configure.ac    2016-01-21 12:55:17.328208650 +0200
+++ tmp/configure.ac    2016-01-21 12:58:59.936204037 +0200
@@ -2,10 +2,10 @@
 # Process this file with autoconf to produce a configure script.

 AC_PREREQ(2.61)
-AC_INIT(BoNeSi, 0.1.1, markus.goldstein@dfki.de)
-AM_INIT_AUTOMAKE(bonesi, 0.1.1)
+AC_INIT([bonesi], [0.1.1], [markus.goldstein@dfki.de])
 AC_OUTPUT(Makefile src/Makefile man/Makefile)
-AC_CONFIG_SRCDIR(src/bonesi.c)
+AC_CONFIG_SRCDIR([src/bonesi.c])
+AM_INIT_AUTOMAKE
 AM_CONFIG_HEADER(config.h)
```

**Comment by Markus-Go** [comment]
Thank you for pointing this out!

**Comment by meenakshi510** [comment]
I'm getting the following error while installing bonesi. Kindly help

:~/Downloads/bonesi-master$ ./configure
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating man/Makefile
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking for pcap_open_live in -lpcap... no
checking for pthread_create in -lpthread... yes
checking for libnet_init in -lnet... yes
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking pcap.h usability... no
checking pcap.h presence... no
checking for pcap.h... no
configure: error: header missing

:~/Downloads/bonesi-master$ make
cd . && /bin/bash ./config.status config.h
config.status: error: invalid argument: `config.h'
make: *** [Makefile:338: stamp-h1] Error 1

:~/Downloads/bonesi-master$ make install
Making install in src
make[1]: Entering directory '/home/mm/Downloads/bonesi-master/src'
Makefile:338: *** missing separator.  Stop.
make[1]: Leaving directory '/home/mm/Downloads/bonesi-master/src'
make: *** [Makefile:354: install-recursive] Error 1

**Comment by Markus-Go** [comment]
configure script complains about missing headerfiles for libpcap, please install them.

**Comment by meenakshi510** [comment]
@Markus-Go Thank you so much. After installing libpcap, bonesi is successfully installed.

What is -d (network listening device) option used for? Is it for the target (victim) device?

**Comment by Markus-Go** [comment]
If you are are using HTTP-GET attacks you need to establish a TCP connection with a 3 way handshake. For that reason, bonesi needs to listen on all incoming traffic on the interface specified with "-d". Make sure, you are setting up your network such that all traffic is routed back to your machine running bonesi, not to the internet.

**Comment by meenakshi510** [comment]
@Markus-Go That's means the -d refers to the interface of the bonesi machine that is generating the traffic.

Thank you so much.

**Comment by meenakshi510** [comment]
@ Markus-Go If machine A has been installed with bonesi and machine B is
the victim. Machine A has the interface eth0 and machine B has the
interface eth1. Then should we use the following:
 -d eth0

**Comment by meenakshi510** [comment]
@ Markus-Go If machine A has been installed with bonesi and machine B is
the victim. Machine A has the interface eth0 and machine B has the
interface eth1. Then should we use the following:
 -d eth0

**Comment by meenakshi510** [comment]
@Markus-Go/bonesi
After installing libpcap, bonesi is successfully installed.
Thank you so much.
