### ISSUE TITLE
i got this problem

### ISSUE THREAD

**Issue by ghettosoulja** [Markus-Go/bonesi#29]
Making install in src
make[1]: Entering directory `/home/user/contiki/examples/ipv6/bonesi-master/src'
make[2]: Entering directory `/home/user/contiki/examples/ipv6/bonesi-master/src'
test -z "/usr/local/bin" || /bin/mkdir -p "/usr/local/bin"
  /usr/bin/install -c bonesi '/usr/local/bin'
/usr/bin/install: cannot create regular file `/usr/local/bin/bonesi': Permission denied
make[2]: *** [install-binPROGRAMS] Error 1
make[2]: Leaving directory `/home/user/contiki/examples/ipv6/bonesi-master/src'
make[1]: *** [install-am] Error 2
make[1]: Leaving directory `/home/user/contiki/examples/ipv6/bonesi-master/src'
make: *** [install-recursive] Error 1

please help me solving this

**Comment by Markus-Go** [comment]
Make sure the directory /usr/local/bin exists and that you have permission to write into it.

**Comment by ghettosoulja** [comment]
hello sir, can you give me the step to d that action.because the directory
that you mention do exist in my ubuntu and when i run your codes this will
appear as i give in attachment. please help me to show the step to fix this
sir, thank you

On Sun, Mar 26, 2017 at 11:11 PM, Markus Goldstein <notifications@github.com
