### ISSUE TITLE
automake 1.15

### ISSUE THREAD

**Issue by ehmueller** [Markus-Go/bonesi#32]
Can you please update the package to support automake 1.15 so I can run the tool on ubuntu 16.04 please?

Below is the failure message I receive.

:~/bonesi$ make
 cd . && automake-1.14 --foreign
/bin/bash: line 4: automake-1.14: command not found
Makefile:289: recipe for target 'Makefile.in' failed
make: *** [Makefile.in] Error 1

Here is the version of automake i have installed.

$ dpkg -l |grep automake
ii  automake                             1:1.15-4ubuntu1                            all          Tool for generating GNU Standards-compliant Makefiles

thanks,
Eric

**Comment by Markus-Go** [comment]
Automake updated to 1.15.

**Comment by ehmueller** [comment]
Thank you!! , I love this tool!
