### ISSUE TITLE
just code I don't understand, thanks in advanced

### ISSUE THREAD

**Issue by GUSTAVO874** [Markus-Go/bonesi#34]
We can find next code in bonesi -> tcpoptions.h. Could please somebody tell my What this code means:
memcpy(tcpOptions[1].options,
           "\002\004\005\264\001\003\003\000\001\001\010\012\000\165\012\042\000\000\000\000",
           //   02 04 05 b4 01 03 03 00 01 01
           //   08 0a 00 75 0a 22 00 00 00 00
           tcpOptions[1].length);
   I don't get why is puting those octal numbers in the array. Below add more code just for context (complete code in tcpoptions.h)
 tcpOptions[1].prob = 0.46f / 3.f;
    tcpOptions[1].length = 20;
    tcpOptions[1].options = (u_int8_t*)malloc(tcpOptions[1].length);
    memcpy(tcpOptions[1].options,
           "\002\004\005\264\001\003\003\000\001\001\010\012\000\165\012\042\000\000\000\000",
           //   02 04 05 b4 01 03 03 00 01 01
           //   08 0a 00 75 0a 22 00 00 00 00
           tcpOptions[1].length);
    
    tcpOptions[2].prob = 0.46f / 3.f;
    tcpOptions[2].length = 20;
    tcpOptions[2].options = (u_int8_t*)malloc(tcpOptions[2].length);
    memcpy(tcpOptions[2].options,
           "\002\004\005\226\004\002\010\012\155\264\137\256\000\000\000\000\001\003\003\000",
           //   02 04 05 96 04 02 08 0a 6d b4
           //   5f ae 00 00 00 00 01 03 03 00
tcpOptions[2].length
.......
........
   Thanks in advanced.

**Comment by Markus-Go** [comment]
Hi Gustavo,

Within the TCP header you can set some options (e.g. for MTU, ACK behavior and other stuff). See https://en.wikipedia.org/wiki/Transmission_Control_Protocol#TCP_segment_structure

We are just putting in there some options, which we have observed in regular traffic by chance. It is not really necessary, but we found that some commercial devices looking for that and filtering out traffic, e.g. with no options set.

Best regards!

**Comment by GUSTAVO874** [comment]
Thank you very much for taking the time for answering, best regards
