### ISSUE TITLE
can't install in centos6.8

### ISSUE THREAD

**Issue by fdgggy** [Markus-Go/bonesi#35]
checking for pcap_open_live in -lpcap... no
checking for pthread_create in -lpthread... yes
checking for libnet_init in -lnet... no
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for stdlib.h... (cached) yes
checking for string.h... (cached) yes
checking for unistd.h... (cached) yes
checking pthread.h usability... yes
checking pthread.h presence... yes
checking for pthread.h... yes
checking pcap.h usability... no
checking pcap.h presence... no
checking for pcap.h... no
configure: error: header missing

i have already install the libnet  and  libpcap1.4,  but it wont work, help me plz

**Comment by linxon** [comment]
do you have `pcap.h` header file in `/usr/include/pcap` ?
https://github.com/Markus-Go/bonesi/blob/5fbdc6018439fba4f4c559bc4dc3d2e80eb4f105/configure.ac#L22

maybe you need to to install libpcap-devel?

**Comment by Markus-Go** [comment]
You need to install the **header** files for the libraries you mentioned.
