### ISSUE TITLE
Generating different traffic rates 

### ISSUE THREAD

**Issue by teamthanos** [Markus-Go/bonesi#38]
How do I go about generating different traffic rates?

If i have to generate 10, 20, 30 MB/s of data volume, what parameters should I use? Should I experiment with trial and error? Or there's a way to find the needed value and options. 

Thanks in advance

**Comment by Markus-Go** [comment]
You can easily generate x MBit/s (or MB/s) by using the two parameters:

-r, --send_rate=NUM             packets per second, 0 = infinite (default)
-s, --payload_size=SIZE          size of the paylod, (default: 32)

You can choose the parameters depending on how you want to fill the bandwidth: 
Many small packets vs. fewer larger packets.
