### ISSUE TITLE
Bonesi Seems to slow myself down, while not really doing anything.

### ISSUE THREAD

**Issue by Motzumoto** [Markus-Go/bonesi#40]
trying to take down my own website hosted on glitch, it seems to just slow me down while not touching the website, anyone know why?

**Comment by Markus-Go** [comment]
Bonesi is a tool to test DDoS defense algorithms/hardware in a closed environment by simulating many clients. Please don't use the tool to attack random servers in the internet.

To answer your question:
In case you used a flooding attack, probably the glitch server has a better internet connection than you have.
